# Generated by Django 3.0.4 on 2020-09-04 07:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=200)),
                ('story', models.TextField(default='Story')),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stories',
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Track Name', max_length=200)),
                ('artist', models.CharField(default='Artist Name', max_length=200)),
                ('description', models.TextField(default='Track Description')),
                ('youtube_link', models.CharField(default='Youtube URL', max_length=200)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Chill', 'CHILL'), ('Pop', 'POP')], default='Pop', max_length=50), default=list, size=None)),
                ('email', models.EmailField(default='email_address', max_length=254)),
                ('cover', models.CharField(default='Selected Album Art', max_length=200)),
                ('proposed_covers', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='images/'), default=list, size=None)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='app.Stories')),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
    ]
