# Generated by Django 3.0.4 on 2020-09-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_trackimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='track_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_image', to='app.TrackImage'),
        ),
    ]
