# Generated by Django 3.0.4 on 2020-09-05 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Tags', max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Tags', max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
