# Generated by Django 3.0.4 on 2020-09-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200905_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='lyrics',
            field=models.TextField(default='Track Lyrics'),
        ),
    ]
