# Generated by Django 3.0.4 on 2020-09-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tracks_lyrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlists',
            options={'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='trackimage',
            options={'verbose_name_plural': 'Track Images'},
        ),
        migrations.AlterModelOptions(
            name='tracks',
            options={'verbose_name_plural': 'Tracks'},
        ),
    ]
