# Generated by Django 3.0.4 on 2020-09-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200906_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='email',
            field=models.EmailField(default='User Email Address', max_length=254),
        ),
        migrations.AddField(
            model_name='stories',
            name='title',
            field=models.CharField(default='Story Title', max_length=200),
        ),
    ]
