# Generated by Django 3.0.4 on 2020-09-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200909_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='social_handle',
            field=models.CharField(default='Artist Social Handle', max_length=200),
        ),
        migrations.AlterField(
            model_name='stories',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=200),
        ),
    ]
