# Generated by Django 3.0.4 on 2020-09-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200914_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='description',
            field=models.TextField(blank=True, default='Track Description', null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='lyrics',
            field=models.TextField(blank=True, default='Track Lyrics', null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='social_handle',
            field=models.CharField(blank=True, default='Artist Social Handle Link', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='youtube_link',
            field=models.CharField(blank=True, default='Youtube URL', max_length=200, null=True),
        ),
    ]
