# Generated by Django 3.0.4 on 2020-09-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='prompt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='track_image', to='app.Prompts'),
        ),
    ]
