# Generated by Django 3.0.4 on 2020-09-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_stories_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='prompt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='track_image', to='app.Prompts'),
        ),
    ]
