# Generated by Django 3.0.4 on 2020-09-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='name',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
