# Generated by Django 3.0.4 on 2020-09-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_stories_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='proposed_covers',
        ),
    ]
