# Generated by Django 3.0.4 on 2020-09-04 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tracks_track_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Tag Name', max_length=200)),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='tracks',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='Tags', max_length=200), default=list, size=None),
        ),
    ]
