# Generated by Django 3.0.4 on 2020-09-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200907_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackimage',
            name='contributor',
            field=models.CharField(default='Contributor Name', max_length=200),
        ),
    ]
