# Generated by Django 3.0.4 on 2020-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_trackimage_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackimage',
            name='email',
            field=models.EmailField(default="Contributor's Email", max_length=254),
        ),
    ]
