# Generated by Django 3.0.4 on 2020-09-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_trackimage_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
    ]
