# Generated by Django 3.0.4 on 2020-09-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200922_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='app.Prompts'),
        ),
    ]
